export const ACTIVITY_LIST_REQUEST = 'ACTIVITY_LIST_REQUEST'
export const ACTIVITY_LIST_SUCCESS = 'ACTIVITY_LIST_SUCCESS'
export const ACTIVITY_LIST_FAIL = 'ACTIVITY_LIST_FAIL'

export const ACTIVITY_ADD_REQUEST = 'ACTIVITY_ADD_REQUEST'
export const ACTIVITY_ADD_SUCCESS = 'ACTIVITY_ADD_SUCCESS'
export const ACTIVITY_ADD_FAIL = 'ACTIVITY_ADD_FAIL'