export const LIST_AGENT_REQUEST = 'LIST_AGENT_REQUEST'

export const LIST_AGENT_SUCCESS = 'LIST_AGENT_SUCCESS'

export const LIST_AGENT_FAIL = 'LIST_AGENT_FAIL'

export const ADD_AGENT_FAIL = 'ADD_AGENT_FAIL'

export const ADD_AGENT_SUCCESS = 'ADD_AGENT_SUCCESS'
export const ADD_AGENT_REQUEST = 'ADD_AGENT_REQUEST'
