export const LIST_AGENT_REQUEST = 'LIST_AGENT_REQUEST'

export const LIST_AGENT_SUCCESS = 'LIST_AGENT_SUCCESS'

export const LIST_AGENT_FAIL = 'LIST_AGENT_FAIL'

export const ADD_AGENT_FAIL = 'ADD_AGENT_FAIL'

export const ADD_AGENT_SUCCESS = 'ADD_AGENT_SUCCESS'
export const ADD_AGENT_REQUEST = 'ADD_AGENT_REQUEST'

export const BAN_AGENT_FAIL = 'BAN_AGENT_FAIL'

export const BAN_AGENT_REQUEST = 'BAN_AGENT_REQUEST'

export const BAN_AGENT_SUCCESS = 'BAN_AGENT_SUCCESS'

export const UNBAN_AGENT_REQUEST = 'UNBAN_AGENT_REQUEST'

export const UNBAN_AGENT_FAIL = 'UNBAN_AGENT_FAIL'

export const UNBAN_AGENT_SUCCESS = 'UNBAN_AGENT_SUCCESS'

export const REMOVE_AGENT_REQUEST = 'REMOVE_AGENT_REQUEST'

export const REMOVE_AGENT_SUCCESS = 'REMOVE_AGENT_SUCCESS'

export const REMOVE_AGENT_FAIL = 'REMOVE_AGENT_FAIL'
