export const LIST_COLLECTIONS_REQUEST = 'LIST_COLLECTIONS_REQUEST'

export const LIST_COLLECTIONS_SUCCESS = 'LIST_COLLECTIONS_SUCCESS'

export const LIST_COLLECTIONS_FAIL = 'LIST_COLLECTIONS_FAIL'

export const LIST_CONTENT_SUCCESS = 'LIST_CONTENT_SUCCESS'
export const LIST_CONTENT_REQUEST = 'LIST_CONTENT_REQUEST'
export const LIST_CONTENT_FAIL = 'LIST_CONTENT_FAIL'

export const ADD_COLLECTION_REQUEST = 'ADD_COLLECTION_REQUEST'

export const ADD_COLLECTION_SUCCESS = 'ADD_COLLECTION_SUCCESS'

export const ADD_COLLECTION_FAIL = 'ADD_COLLECTION_FAIL'

export const ADD_RATE_REQUEST = 'ADD_RATE_REQUEST'
export const ADD_RATE_SUCCESS = 'ADD_RATE_SUCCESS'
export const ADD_RATE_FAIL = 'ADD_RATE_FAIL'

export const UPDATE_RATE_SUCCESS = 'UPDATE_RATE_SUCCESS'

export const UPDATE_RATE_REQUEST = 'UPDATE_RATE_REQUEST'
export const UPDATE_RATE_FAIL = 'UPDATE_RATE_FAIL'

export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST'
export const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL'
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS'

export const REMOVE_NOTE_REQUEST = 'REMOVE_NOTE_REQUEST'
export const REMOVE_NOTE_FAIL = 'REMOVE_NOTE_FAIL'
export const REMOVE_NOTE_SUCCESS = 'REMOVE_NOTE_SUCCESS'

export const REMOVE_EVENT_REQUEST = 'REMOVE_EVENT_REQUEST'
export const REMOVE_EVENT_SUCCESS = 'REMOVE_EVENT_SUCCESS'
export const REMOVE_EVENT_FAIL = 'REMOVE_EVENT_FAIL'

export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST'
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS'
export const ADD_EVENT_FAIL = 'ADD_EVENT_FAIL'
