export const ADD_MEET_REQUEST = 'ADD_MEET_REQUEST'

export const ADD_MEET_SUCCESS = 'ADD_MEET_SUCCESS'

export const ADD_MEET_FAIL = 'ADD_MEET_FAIL'

export const GET_MEETS_SUCCESS = 'GET_MEETS_SUCCESS'
export const GET_MEETS_REQUEST = 'GET_MEETS_REQUEST'

export const GET_MEETS_FAIL = 'GET_MEETS_FAIL'

export const CANCEL_MEET_REQUEST = 'CANCEL_MEET_REQUEST'
export const CANCEL_MEET_SUCCESS = 'CANCEL_MEET_SUCCESS'
export const CANCEL_MEET_FAIL = 'CANCEL_MEET_FAIL'
