export const PROFILE_LIST_REQUEST = 'PROFILE_LIST_REQUEST'
export const PROFILE_LIST_SUCCESS = 'PROFILE_LIST_SUCCESS'
export const PROFILE_LIST_FAIL = 'PROFILE_LIST_FAIL'




//testing versions
export const SAME_PROFILE_REQUEST = 'SAME_PROFILE_REQUEST'
export const SAME_PROFILE_SUCCESS = 'SAME_PROFILE_SUCCESS'
export const SAME_PROFILE_FAIL = 'SAME_PROFILE_FAIL'