export const SETTINGS_LIST_REQUEST = 'SETTINGS_LIST_REQUEST'
export const SETTINGS_LIST_SUCCESS = 'SETTINGS_LIST_SUCCESS'
export const SETTINGS_LIST_FAIL = 'SETTINGS_LIST_FAIL'

export const SETTINGS_ADD_REQUEST = 'SETTINGS_ADD_REQUEST'
export const SETTINGS_ADD_SUCCESS = 'SETTINGS_ADD_SUCCESS'
export const SETTINGS_ADD_FAIL = 'SETTINGS_ADD_FAIL'


export const SETTINGS_DELETE_REQUEST = 'SETTINGS_DELETE_REQUEST'
export const SETTINGS_DELETE_SUCCESS = 'SETTINGS_DELETE_SUCCESS'
export const SETTINGS_DELETE_FAIL = 'SETTINGS_DELETE_FAIL'


export const SETTINGS_EDIT_REQUEST = 'SETTINGS_EDIT_REQUEST'
export const SETTINGS_EDIT_SUCCESS = 'SETTINGS_EDIT_SUCCESS'
export const SETTINGS_EDIT_FAIL = 'SETTINGS_EDIT_FAIL'
export const SETTINGS_UPDATE_RESET = 'SETTINGS_UPDATE_RESET'
