export const SETTINGS_LIST_REQUEST = 'SETTINGS_LIST_REQUEST'
export const SETTINGS_LIST_SUCCESS = 'SETTINGS_LIST_SUCCESS'
export const SETTINGS_LIST_FAIL = 'SETTINGS_LIST_FAIL'

export const SETTINGS_ADD_REQUEST = 'SETTINGS_ADD_REQUEST'
export const SETTINGS_ADD_SUCCESS = 'SETTINGS_ADD_SUCCESS'
export const SETTINGS_ADD_FAIL = 'SETTINGS_ADD_FAIL'